// <auto-generated />
namespace Gerenciador.Repository.EntityFramwork.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddDoneToTodoItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDoneToTodoItem));
        
        string IMigrationMetadata.Id
        {
            get { return "201412150208591_AddDoneToTodoItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
